export const features = [
    {
        id: 1,
        image: "/image/findGallery (3).png",
        title: "Discover LA's Dining Scene",
        description:
            "Explore the most popular, trending, and hidden gem restaurants across Los Angeles. Whether you're after casual bites or upscale dining, we've got it covered.",
    },
    {
        id: 2,
        image: "/image/findGallery (2).png",
        title: "Find Spots by Vibe & Cuisine",
        description:
            "Search smarter with filters like mood, ambiance, and cuisine. From rooftop vibes to cozy corners, find places that fit your energy and cravings.",
    },
    {
        id: 3,
        image: "/image/findGallery (1).png",
        title: "Real-Time Trends & Hot Picks",
        description:
            "Stay in the loop with what's buzzing. Our Trend Score™ and curated lists keep you updated with new openings, viral hotspots, and crowd favorites.",
    },
]


export const restaurantData = [
    {
        id: 1,
        name: "Paloma Kitchen",
        image: "/image/nearby (4).png",
        rating: 4.8,
        reviews: 248,
        tags: ["Rooftop", "Italian"],
        location: "Beverly Crest, Los Angeles",
        hours: "09:00 AM - 11 PM",
    },
    {
        id: 2,
        name: "Paloma Kitchen",
        image: "/image/nearby (3).png",
        rating: 4.8,
        reviews: 248,
        tags: ["Rooftop", "Italian"],
        location: "Beverly Crest, Los Angeles",
        hours: "09:00 AM - 11 PM",
    },
    {
        id: 3,
        name: "Paloma Kitchen",
        image: "/image/nearby (2).png",
        rating: 4.8,
        reviews: 248,
        tags: ["Rooftop", "Italian"],
        location: "Beverly Crest, Los Angeles",
        hours: "09:00 AM - 11 PM",
    },
    {
        id: 4,
        name: "Paloma Kitchen",
        image: "/image/nearby (1).png",
        rating: 4.8,
        reviews: 248,
        tags: ["Rooftop", "Italian"],
        location: "Beverly Crest, Los Angeles",
        hours: "09:00 AM - 11 PM",
    },
    {
        id: 5,
        name: "Paloma Kitchen",
        image: "/image/nearby (4).png",
        rating: 4.8,
        reviews: 248,
        tags: ["Rooftop", "Italian"],
        location: "Beverly Crest, Los Angeles",
        hours: "09:00 AM - 11 PM",
    },
    {
        id: 6,
        name: "Paloma Kitchen",
        image: "/image/nearby (2).png",
        rating: 4.8,
        reviews: 248,
        tags: ["Rooftop", "Italian"],
        location: "Beverly Crest, Los Angeles",
        hours: "09:00 AM - 11 PM",
    },
    {
        id: 7,
        name: "Paloma Kitchen",
        image: "/image/nearby (3).png",
        rating: 4.8,
        reviews: 248,
        tags: ["Rooftop", "Italian"],
        location: "Beverly Crest, Los Angeles",
        hours: "09:00 AM - 11 PM",
    },
    {
        id: 8,
        name: "Paloma Kitchen",
        image: "/image/nearby (2).png",
        rating: 4.8,
        reviews: 248,
        tags: ["Rooftop", "Italian"],
        location: "Beverly Crest, Los Angeles",
        hours: "09:00 AM - 11 PM",
    },
    {
        id: 9,
        name: "Paloma Kitchen",
        image: "/image/nearby (1).png",
        rating: 4.8,
        reviews: 248,
        tags: ["Rooftop", "Italian"],
        location: "Beverly Crest, Los Angeles",
        hours: "09:00 AM - 11 PM",
    },
    {
        id: 10,
        name: "Paloma Kitchen",
        image: "/image/nearby (4).png",
        rating: 4.8,
        reviews: 248,
        tags: ["Rooftop", "Italian"],
        location: "Beverly Crest, Los Angeles",
        hours: "09:00 AM - 11 PM",
    },
]

// Filter categories
