import "./globals.css";
import { Toaster } from "react-hot-toast";
import { Inter } from "next/font/google";
import RootLayoutClient from "./RootLayoutClient";

const inter = Inter({ subsets: ["latin"] });



export const metadata = {
  title: "LAEatery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body
        className={`${inter.className}`}
      >
        
        <Toaster />
        <RootLayoutClient>{children}</RootLayoutClient>
      </body>
    </html>
  );
}
