import "./globals.css";
import { Toaster } from "react-hot-toast";
import RootLayoutClient from "./RootLayoutClient";
import { Inter, Poltawski_Nowy } from 'next/font/google'
import { ThemeProvider } from "@/context/ThemeContext";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

const poltawski = Poltawski_Nowy({
  subsets: ['latin'],
  variable: '--font-poltawski',
})



export const metadata = {
  title: "LAEatery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster />
        <ThemeProvider>
          <div className={`${inter.variable} ${poltawski.variable} bg-[#E9E7E3]`}>
            <RootLayoutClient>{children}</RootLayoutClient>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
