import "./globals.css";
import { Toaster } from "react-hot-toast";

import RootLayoutClient from "./RootLayoutClient";


export const metadata = {
  title: "LAEatery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />
        <RootLayoutClient>{children}</RootLayoutClient>
      </body>
    </html>
  );
}
